[package]
name = "bi5_converter"
version = "0.1.0"
edition = "2021"

[dependencies]
lzma-rs = "0.3"
byteorder = "1.4"
chrono = { version = "0.4", features = ["serde"] }
csv = "1.2"
parquet = "55.2.0"
arrow = "55.2.0"
rayon = "1.10.0"
lzma = "0.2.2"
